spring:
  application:
    name: rh-crm-service
  config:
    import:
      - optional:classpath:/common.yml
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://rm-2zetkh468264c9i92yo.mysql.rds.aliyuncs.com:3306/ruihong?serverTimezone=UTC&useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: ruihong
    password: RuiHong@008

feign:
  client:
    jinshuju-api:
      url: https://jinshuju.net
      token: Basic ajY3S00yTVhaeDhxNWVXYlEwdHhHUTo0YmtPVnAzSkUzUy1WWTJsRFhHR2t3

app:
  jsj-form-labels-for-name: [姓名,称呼,名字]
  jsj-form-labels-for-mobile: [手机号,手机号码,手机]
